# Generated by Django 6.0.1 on 2026-02-02 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('feed', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='karmatransaction',
            name='source_content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='karmatransaction',
            name='source_object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post'], name='feed_commen_post_id_8a1e56_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent'], name='feed_commen_parent__bf3cb4_idx'),
        ),
        migrations.AddIndex(
            model_name='karmatransaction',
            index=models.Index(fields=['source_content_type', 'source_object_id'], name='feed_karmat_source__c4849d_idx'),
        ),
    ]
